import React, { useState } from 'react';
import { 
  TargetResult, 
  ThemeColor 
} from '../types';
import { 
  MapPin, 
  Smartphone, 
  Wifi, 
  ShieldAlert, 
  Download, 
  Copy, 
  Check, 
  Share2, 
  Radio, 
  Battery, 
  BatteryCharging, 
  Cpu, 
  Globe, 
  AlertTriangle, 
  ExternalLink,
  Lock,
  Eye,
  RefreshCw,
  Search
} from 'lucide-react';
import { playKeySound } from '../utils/audio';

interface TargetDossierProps {
  result: TargetResult;
  themeColor: ThemeColor;
  onNewScan: () => void;
}

export const TargetDossier: React.FC<TargetDossierProps> = ({
  result,
  themeColor,
  onNewScan
}) => {
  const [activeTab, setActiveTab] = useState<'overview' | 'location' | 'device' | 'network' | 'security' | 'social'>('overview');
  const [copied, setCopied] = useState<boolean>(false);
  const [pinging, setPinging] = useState<boolean>(false);
  const [pingTime, setPingTime] = useState<number>(21);

  const handleCopyReport = () => {
    playKeySound();
    const report = `========================================================
           KRAH-TOOLS INTELLIGENCE TARGET DOSSIER
========================================================
TRACKING ID     : ${result.trackingId}
TIMESTAMP       : ${result.timestamp}
QUERY INPUT     : ${result.query} (${result.queryType.toUpperCase()})

[1] IDENTITAS TARGET
--------------------------------------------------------
Nama Lengkap    : ${result.name}
Gender / Usia   : ${result.gender} / ${result.age} Tahun
Nomor Telepon   : ${result.phone}
Email           : ${result.email}
Hash NIK/ID     : ${result.nikHash}

[2] LOKASI & GEOLOCATION SATELIT
--------------------------------------------------------
Alamat Lengkap  : ${result.location.address}
Kota / Provinsi : ${result.location.city}, ${result.location.province}
Negara / KodePos: ${result.location.country} (${result.location.postalCode})
Koordinat GPS   : LAT ${result.location.latitude} | LNG ${result.location.longitude}
Ketinggian / Acc: ${result.location.altitude} | ${result.location.accuracy}

[3] HARDWARE & PERANGKAT
--------------------------------------------------------
Model Perangkat : ${result.device.model}
Vendor / OS     : ${result.device.vendor} (${result.device.os})
Baterai         : ${result.device.batteryLevel}% [${result.device.batteryStatus}]
IMEI / MAC      : ${result.device.imei} | ${result.device.macAddress}

[4] TELEMETRI JARINGAN & CARRIER
--------------------------------------------------------
Provider / ISP  : ${result.network.carrier} (${result.network.isp})
IP Publik       : ${result.network.ip}
Tower ID BTS    : ${result.network.towerId} (MCC/MNC: ${result.network.mccMnc})
Sinyal Seluler  : ${result.network.signalDbm} dBm
Port Terbuka    : ${result.network.openPorts.join(', ')}

========================================================
Generated by Krah-Tools Reconnaissance System
========================================================`;

    navigator.clipboard.writeText(report);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadReport = () => {
    playKeySound();
    const element = document.createElement('a');
    const file = new Blob([
      `KRAH-TOOLS INTELLIGENCE DOSSIER\nTarget: ${result.query}\nName: ${result.name}\nLocation: ${result.location.address}, ${result.location.city}\nCoordinates: ${result.location.latitude}, ${result.location.longitude}\nIP: ${result.network.ip}\nIMEI: ${result.device.imei}\nTracking ID: ${result.trackingId}\nTimestamp: ${new Date().toISOString()}`
    ], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `DOSSIER_${result.trackingId}_${result.name.replace(/\s+/g, '_')}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const triggerPing = () => {
    playKeySound();
    setPinging(true);
    setTimeout(() => {
      setPingTime(Math.floor(14 + Math.random() * 18));
      setPinging(false);
    }, 600);
  };

  // Google Maps or OSM link
  const mapsUrl = `https://www.google.com/maps?q=${result.location.latitude},${result.location.longitude}`;

  return (
    <div id="target-dossier-card" className="w-full bg-slate-900/90 border border-slate-800 rounded-xl p-4 sm:p-7 shadow-2xl backdrop-blur-xl space-y-6">
      {/* Top Banner with Target Profile Overview */}
      <div className="bg-slate-950/80 border border-slate-800 rounded-xl p-5 relative overflow-hidden">
        <div className="absolute top-0 right-0 px-4 py-1.5 bg-emerald-950/80 border-b border-l border-emerald-500/40 text-emerald-400 font-mono text-xs flex items-center gap-2">
          <span className="w-2 h-2 rounded-full bg-emerald-400 animate-ping"></span>
          <span>STATUS: TARGET TERKUNCI & TERLACAK</span>
        </div>

        <div className="flex flex-col md:flex-row items-center md:items-start gap-5 pt-4 md:pt-0">
          {/* Target Photo Box */}
          <div className="relative group">
            <div className="w-28 h-28 sm:w-32 sm:h-32 rounded-xl overflow-hidden border-2 border-emerald-500/60 shadow-[0_0_20px_rgba(16,185,129,0.3)] bg-slate-900 relative">
              <img
                src={result.avatarUrl}
                alt="Target Photo Biometric"
                className="w-full h-full object-cover grayscale contrast-125 group-hover:grayscale-0 transition-all duration-300"
                referrerPolicy="no-referrer"
              />
              {/* Scanline overlay */}
              <div className="absolute inset-0 bg-gradient-to-b from-transparent via-emerald-500/10 to-transparent bg-[length:100%_4px] pointer-events-none"></div>
              {/* Corner reticles */}
              <div className="absolute top-1 left-1 w-2.5 h-2.5 border-t-2 border-l-2 border-emerald-400"></div>
              <div className="absolute bottom-1 right-1 w-2.5 h-2.5 border-b-2 border-r-2 border-emerald-400"></div>
            </div>
            <div className="mt-2 text-center">
              <span className="text-[10px] font-mono bg-emerald-950/90 text-emerald-300 px-2 py-0.5 rounded border border-emerald-500/40">
                BIOMETRIC MATCH 99.4%
              </span>
            </div>
          </div>

          {/* Primary Details */}
          <div className="flex-1 text-center md:text-left space-y-2">
            <div className="flex flex-wrap items-center justify-center md:justify-start gap-2">
              <h2 className="text-xl sm:text-2xl font-black font-mono text-white tracking-wide">
                {result.name}
              </h2>
              <span className="text-xs font-mono px-2 py-0.5 rounded bg-slate-800 text-slate-300 border border-slate-700">
                {result.gender}, {result.age} THN
              </span>
            </div>

            <div className="text-xs sm:text-sm font-mono text-slate-300 space-y-1">
              <div className="flex items-center justify-center md:justify-start gap-2 text-emerald-400">
                <MapPin className="w-4 h-4 flex-shrink-0" />
                <span className="font-semibold">{result.location.city}, {result.location.province}, {result.location.country}</span>
              </div>
              <div className="text-slate-400 text-xs">
                {result.location.address} (Kode Pos: {result.location.postalCode})
              </div>
            </div>

            <div className="pt-2 flex flex-wrap items-center justify-center md:justify-start gap-2 text-xs font-mono">
              <span className="px-2.5 py-1 rounded bg-slate-900 border border-slate-800 text-slate-300">
                PHONE: <strong className="text-white">{result.phone}</strong>
              </span>
              <span className="px-2.5 py-1 rounded bg-slate-900 border border-slate-800 text-slate-300">
                EMAIL: <strong className="text-white">{result.email}</strong>
              </span>
              <span className="px-2.5 py-1 rounded bg-slate-900 border border-slate-800 text-slate-300">
                ID: <strong className="text-emerald-400">{result.trackingId}</strong>
              </span>
            </div>
          </div>

          {/* Action Button Group */}
          <div className="flex flex-row md:flex-col gap-2 w-full md:w-auto">
            <button
              id="copy-dossier-btn"
              type="button"
              onClick={handleCopyReport}
              className="flex-1 md:flex-none px-3.5 py-2 rounded bg-slate-800 hover:bg-slate-700 border border-slate-700 text-slate-200 font-mono text-xs flex items-center justify-center gap-2 transition-colors"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'TERSALIN' : 'SALIN DOSSIER'}</span>
            </button>

            <button
              id="download-dossier-btn"
              type="button"
              onClick={handleDownloadReport}
              className="flex-1 md:flex-none px-3.5 py-2 rounded bg-emerald-600 hover:bg-emerald-500 text-black font-mono font-bold text-xs flex items-center justify-center gap-2 transition-colors shadow-lg shadow-emerald-500/20"
            >
              <Download className="w-3.5 h-3.5" />
              <span>UNDUH LAPORAN</span>
            </button>

            <button
              id="track-new-btn"
              type="button"
              onClick={() => {
                playKeySound();
                onNewScan();
              }}
              className="flex-1 md:flex-none px-3.5 py-2 rounded bg-slate-900 hover:bg-slate-800 border border-slate-700 text-slate-300 font-mono text-xs flex items-center justify-center gap-2 transition-colors"
            >
              <RefreshCw className="w-3.5 h-3.5" />
              <span>LACAK TARGET LAIN</span>
            </button>
          </div>
        </div>
      </div>

      {/* Tabs Navigation */}
      <div className="flex flex-wrap border-b border-slate-800 gap-1 sm:gap-2">
        {[
          { id: 'overview', label: 'Ringkasan Eksekutif', icon: Eye },
          { id: 'location', label: 'Lokasi & Radar GPS', icon: MapPin },
          { id: 'device', label: 'Perangkat & Hardware', icon: Smartphone },
          { id: 'network', label: 'Jaringan & Tower BTS', icon: Wifi },
          { id: 'security', label: 'Kebocoran & Port Audit', icon: ShieldAlert },
          { id: 'social', label: 'Jejak Media Sosial', icon: Globe }
        ].map((tab) => {
          const Icon = tab.icon;
          const isActive = activeTab === tab.id;
          return (
            <button
              key={tab.id}
              id={`tab-btn-${tab.id}`}
              type="button"
              onClick={() => {
                playKeySound();
                setActiveTab(tab.id as typeof activeTab);
              }}
              className={`flex items-center gap-2 px-3.5 py-2.5 rounded-t-lg font-mono text-xs font-semibold transition-all ${
                isActive
                  ? 'bg-slate-950 border-t-2 border-x border-slate-800 border-t-emerald-400 text-emerald-400'
                  : 'text-slate-400 hover:text-slate-200 hover:bg-slate-950/40'
              }`}
            >
              <Icon className="w-3.5 h-3.5" />
              <span>{tab.label}</span>
            </button>
          );
        })}
      </div>

      {/* Tab Contents */}

      {/* 1. Overview Tab */}
      {activeTab === 'overview' && (
        <div id="tab-content-overview" className="space-y-6">
          {/* 3 Metric Cards */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="p-4 rounded-xl bg-slate-950 border border-slate-800">
              <span className="text-xs font-mono text-slate-400 block mb-1">TINGKAT AKURASI KOORDINAT</span>
              <div className="text-xl font-bold font-mono text-emerald-400">
                {result.location.accuracy.split(' ')[0]} {result.location.accuracy.split(' ')[1]} {result.location.accuracy.split(' ')[2]}
              </div>
              <span className="text-[11px] font-mono text-slate-500">11 Satelit NAVSTAR Terhubung</span>
            </div>

            <div className="p-4 rounded-xl bg-slate-950 border border-slate-800">
              <span className="text-xs font-mono text-slate-400 block mb-1">STATUS DAYA PERANGKAT</span>
              <div className="text-xl font-bold font-mono text-cyan-400 flex items-center gap-2">
                <Battery className="w-5 h-5" />
                <span>{result.device.batteryLevel}%</span>
                <span className="text-xs text-slate-400 font-normal">({result.device.batteryStatus})</span>
              </div>
              <span className="text-[11px] font-mono text-slate-500">Model: {result.device.model}</span>
            </div>

            <div className="p-4 rounded-xl bg-slate-950 border border-slate-800">
              <span className="text-xs font-mono text-slate-400 block mb-1">SKOR ANCAMAN KEAMANAN</span>
              <div className="text-xl font-bold font-mono text-amber-400 flex items-center gap-2">
                <AlertTriangle className="w-5 h-5" />
                <span>{result.security.threatScore} / 100</span>
              </div>
              <span className="text-[11px] font-mono text-slate-500">{result.security.leakedDatabases.length} Database Bocor Ditemukan</span>
            </div>
          </div>

          {/* Key Facts Summary Table */}
          <div className="bg-slate-950/80 rounded-xl border border-slate-800 p-5 font-mono text-xs">
            <h3 className="text-sm font-bold text-white mb-4 pb-2 border-b border-slate-800 flex items-center gap-2">
              <Lock className="w-4 h-4 text-emerald-400" />
              PARAMETER DATA INTELIJEN TERVALIDASI
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-y-3 gap-x-8">
              <div className="flex justify-between py-1 border-b border-slate-900">
                <span className="text-slate-400">Target Identifier:</span>
                <span className="text-white font-bold">{result.query}</span>
              </div>
              <div className="flex justify-between py-1 border-b border-slate-900">
                <span className="text-slate-400">Alamat Tempat Tinggal:</span>
                <span className="text-white font-bold text-right truncate max-w-[220px]">{result.location.address}</span>
              </div>
              <div className="flex justify-between py-1 border-b border-slate-900">
                <span className="text-slate-400">Wilayah / Kota:</span>
                <span className="text-emerald-400 font-bold">{result.location.city}, {result.location.province}</span>
              </div>
              <div className="flex justify-between py-1 border-b border-slate-900">
                <span className="text-slate-400">Koordinat GPS Satelit:</span>
                <span className="text-cyan-400 font-bold">{result.location.latitude}, {result.location.longitude}</span>
              </div>
              <div className="flex justify-between py-1 border-b border-slate-900">
                <span className="text-slate-400">Nomor IMEI Handset:</span>
                <span className="text-white">{result.device.imei}</span>
              </div>
              <div className="flex justify-between py-1 border-b border-slate-900">
                <span className="text-slate-400">Alamat IP Publik:</span>
                <span className="text-emerald-400 font-bold">{result.network.ip}</span>
              </div>
              <div className="flex justify-between py-1 border-b border-slate-900">
                <span className="text-slate-400">Operator Seluler:</span>
                <span className="text-white">{result.network.carrier}</span>
              </div>
              <div className="flex justify-between py-1 border-b border-slate-900">
                <span className="text-slate-400">Sistem Operasi:</span>
                <span className="text-white">{result.device.os}</span>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* 2. Location & Satellite Tab */}
      {activeTab === 'location' && (
        <div id="tab-content-location" className="space-y-6">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
            {/* Interactive Dark Grid Visualizer */}
            <div className="lg:col-span-7 bg-slate-950 rounded-xl border border-slate-800 p-5 relative overflow-hidden flex flex-col justify-between min-h-[340px]">
              {/* Map grid background */}
              <div className="absolute inset-0 bg-[radial-gradient(#1e293b_1px,transparent_1px)] [background-size:20px_20px] opacity-60"></div>
              
              {/* Target pin in map visualizer */}
              <div className="relative z-10 flex flex-col items-center justify-center my-auto py-8">
                <div className="relative flex items-center justify-center">
                  <div className="w-32 h-32 rounded-full border border-emerald-500/30 bg-emerald-500/5 animate-ping absolute"></div>
                  <div className="w-20 h-20 rounded-full border border-emerald-400/50 bg-emerald-500/10 flex items-center justify-center relative">
                    <div className="w-8 h-8 rounded-full bg-emerald-500/20 border-2 border-emerald-400 flex items-center justify-center shadow-[0_0_15px_rgba(16,185,129,0.8)]">
                      <div className="w-3 h-3 rounded-full bg-emerald-400 animate-pulse"></div>
                    </div>
                  </div>
                </div>

                <div className="mt-4 bg-slate-900/90 border border-emerald-500/50 px-4 py-2 rounded-lg text-center font-mono shadow-xl">
                  <span className="text-emerald-400 font-bold text-xs block">TARGET LOCATION PINPOINTED</span>
                  <span className="text-white text-xs">{result.location.address}</span>
                  <span className="text-slate-400 text-[11px] block mt-0.5">{result.location.city}, {result.location.province}</span>
                </div>
              </div>

              {/* Coordinates bar */}
              <div className="relative z-10 flex flex-wrap items-center justify-between gap-2 pt-3 border-t border-slate-800 text-xs font-mono text-slate-300">
                <span>LAT: <strong className="text-emerald-400">{result.location.latitude}</strong></span>
                <span>LNG: <strong className="text-emerald-400">{result.location.longitude}</strong></span>
                <span>ALT: <strong className="text-cyan-400">{result.location.altitude}</strong></span>
                <a
                  href={mapsUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="px-3 py-1 bg-emerald-600 hover:bg-emerald-500 text-black font-bold rounded flex items-center gap-1.5 transition-colors"
                >
                  <ExternalLink className="w-3.5 h-3.5" />
                  <span>BUKA GOOGLE MAPS</span>
                </a>
              </div>
            </div>

            {/* Geolocation metadata sidecard */}
            <div className="lg:col-span-5 bg-slate-950 rounded-xl border border-slate-800 p-5 font-mono text-xs space-y-4">
              <h3 className="text-sm font-bold text-white pb-2 border-b border-slate-800 flex items-center gap-2">
                <Globe className="w-4 h-4 text-emerald-400" />
                TELEMETRI LOKASI LENGKAP
              </h3>

              <div className="space-y-3">
                <div>
                  <span className="text-slate-500 block text-[11px]">ALAMAT FISIK TERLACAK:</span>
                  <p className="text-slate-100 font-semibold text-sm mt-0.5 leading-snug">{result.location.address}</p>
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <span className="text-slate-500 block text-[11px]">KOTA / KABUPATEN:</span>
                    <span className="text-white font-bold">{result.location.city}</span>
                  </div>
                  <div>
                    <span className="text-slate-500 block text-[11px]">PROVINSI:</span>
                    <span className="text-white">{result.location.province}</span>
                  </div>
                  <div>
                    <span className="text-slate-500 block text-[11px]">KODE POS:</span>
                    <span className="text-emerald-400 font-bold">{result.location.postalCode}</span>
                  </div>
                  <div>
                    <span className="text-slate-500 block text-[11px]">ZONA WAKTU:</span>
                    <span className="text-white">{result.location.timezone}</span>
                  </div>
                </div>

                <div className="pt-2 border-t border-slate-800 space-y-2">
                  <div className="flex justify-between">
                    <span className="text-slate-400">Radius Presisi GPS:</span>
                    <span className="text-emerald-400 font-bold">{result.location.accuracy}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-400">Altitude Satelit:</span>
                    <span className="text-white">{result.location.altitude}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-slate-400">DOP (Dilution of Precision):</span>
                    <span className="text-cyan-400 font-bold">0.82 (Excellent)</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* 3. Device & Hardware Tab */}
      {activeTab === 'device' && (
        <div id="tab-content-device" className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 font-mono text-xs">
            <div className="bg-slate-950 rounded-xl border border-slate-800 p-5 space-y-4">
              <h3 className="text-sm font-bold text-white pb-2 border-b border-slate-800 flex items-center gap-2">
                <Smartphone className="w-4 h-4 text-cyan-400" />
                SPESIFIKASI PERANGKAT KERAS
              </h3>
              
              <div className="space-y-3">
                <div className="flex justify-between py-1 border-b border-slate-900">
                  <span className="text-slate-400">Model Handset:</span>
                  <span className="text-white font-bold">{result.device.model}</span>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-900">
                  <span className="text-slate-400">Vendor / Manufaktur:</span>
                  <span className="text-white">{result.device.vendor}</span>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-900">
                  <span className="text-slate-400">Sistem Operasi:</span>
                  <span className="text-emerald-400 font-bold">{result.device.os}</span>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-900">
                  <span className="text-slate-400">Resolusi Layar:</span>
                  <span className="text-white">{result.device.screenResolution}</span>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-900">
                  <span className="text-slate-400">Status Keaktifan:</span>
                  <span className="text-emerald-400 font-bold">{result.device.lastActive}</span>
                </div>
              </div>
            </div>

            <div className="bg-slate-950 rounded-xl border border-slate-800 p-5 space-y-4">
              <h3 className="text-sm font-bold text-white pb-2 border-b border-slate-800 flex items-center gap-2">
                <Cpu className="w-4 h-4 text-emerald-400" />
                IDENTIFIKATOR UNIK PERANGKAT
              </h3>

              <div className="space-y-3">
                <div className="flex justify-between py-1 border-b border-slate-900">
                  <span className="text-slate-400">Nomor IMEI:</span>
                  <span className="text-emerald-400 font-bold">{result.device.imei}</span>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-900">
                  <span className="text-slate-400">Alamat MAC Wi-Fi:</span>
                  <span className="text-cyan-400 font-bold">{result.device.macAddress}</span>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-900">
                  <span className="text-slate-400">Kapasitas Baterai:</span>
                  <span className="text-white font-bold">{result.device.batteryLevel}% ({result.device.batteryStatus})</span>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-900">
                  <span className="text-slate-400">Kernel Build:</span>
                  <span className="text-slate-300">Linux 5.15.122-android14-perf</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* 4. Network & BTS Tower Tab */}
      {activeTab === 'network' && (
        <div id="tab-content-network" className="space-y-6 font-mono text-xs">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="bg-slate-950 rounded-xl border border-slate-800 p-5 space-y-4">
              <h3 className="text-sm font-bold text-white pb-2 border-b border-slate-800 flex items-center gap-2">
                <Wifi className="w-4 h-4 text-emerald-400" />
                JARINGAN & OPERATOR SELULER
              </h3>

              <div className="space-y-3">
                <div className="flex justify-between py-1 border-b border-slate-900">
                  <span className="text-slate-400">Nama Provider:</span>
                  <span className="text-white font-bold">{result.network.carrier}</span>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-900">
                  <span className="text-slate-400">ISP Gateway:</span>
                  <span className="text-white">{result.network.isp}</span>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-900">
                  <span className="text-slate-400">Kekuatan Sinyal:</span>
                  <span className="text-emerald-400 font-bold">{result.network.signalDbm} dBm (Sangat Baik)</span>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-900">
                  <span className="text-slate-400">ID Menara Tower BTS:</span>
                  <span className="text-cyan-400 font-bold">{result.network.towerId}</span>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-900">
                  <span className="text-slate-400">Kode MCC / MNC:</span>
                  <span className="text-white">{result.network.mccMnc}</span>
                </div>
              </div>
            </div>

            <div className="bg-slate-950 rounded-xl border border-slate-800 p-5 space-y-4">
              <div className="flex items-center justify-between pb-2 border-b border-slate-800">
                <h3 className="text-sm font-bold text-white flex items-center gap-2">
                  <Radio className="w-4 h-4 text-cyan-400" />
                  GATEWAY INTERNET & PORT
                </h3>
                <button
                  type="button"
                  onClick={triggerPing}
                  className="px-2 py-1 rounded bg-slate-800 hover:bg-slate-700 text-[10px] text-emerald-400 border border-emerald-500/30 flex items-center gap-1"
                >
                  <RefreshCw className={`w-3 h-3 ${pinging ? 'animate-spin' : ''}`} />
                  <span>PING PROBE</span>
                </button>
              </div>

              <div className="space-y-3">
                <div className="flex justify-between py-1 border-b border-slate-900">
                  <span className="text-slate-400">Alamat IPv4 Publik:</span>
                  <span className="text-emerald-400 font-bold">{result.network.ip}</span>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-900">
                  <span className="text-slate-400">Alamat IPv6:</span>
                  <span className="text-slate-300 truncate max-w-[200px]">{result.network.ipv6}</span>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-900">
                  <span className="text-slate-400">RTT Latency (Ping):</span>
                  <span className="text-cyan-400 font-bold">{pingTime} ms</span>
                </div>
                <div className="flex justify-between py-1 border-b border-slate-900">
                  <span className="text-slate-400">Port Aktif Terbuka:</span>
                  <div className="flex gap-1.5 flex-wrap">
                    {result.network.openPorts.map(p => (
                      <span key={p} className="px-1.5 py-0.5 rounded bg-emerald-950 text-emerald-300 border border-emerald-500/40 text-[10px]">
                        :{p}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* 5. Security & Leaks Tab */}
      {activeTab === 'security' && (
        <div id="tab-content-security" className="space-y-6 font-mono text-xs">
          <div className="bg-slate-950 rounded-xl border border-slate-800 p-5 space-y-4">
            <h3 className="text-sm font-bold text-white pb-2 border-b border-slate-800 flex items-center gap-2">
              <ShieldAlert className="w-4 h-4 text-amber-400" />
              DATABASE KEBOCORAN & JEJAK DATA PRIVASI
            </h3>

            <p className="text-slate-400 text-xs">
              Data intelijen menemukan beberapa catatan riwayat akun target yang terdaftar pada arsip publik:
            </p>

            <div className="space-y-2.5">
              {result.security.leakedDatabases.map((leak, idx) => (
                <div key={idx} className="p-3 rounded-lg bg-slate-900 border border-slate-800 flex flex-wrap items-center justify-between gap-3">
                  <div>
                    <div className="text-white font-bold text-xs">{leak.source} ({leak.year})</div>
                    <div className="text-slate-400 text-[11px] mt-0.5">Tipe Data Bocor: {leak.dataType}</div>
                  </div>
                  <span className={`px-2.5 py-1 rounded text-[10px] font-bold border ${
                    leak.riskLevel === 'CRITICAL'
                      ? 'bg-rose-950/80 border-rose-500/60 text-rose-400'
                      : leak.riskLevel === 'HIGH'
                      ? 'bg-amber-950/80 border-amber-500/60 text-amber-400'
                      : 'bg-slate-800 border-slate-700 text-slate-300'
                  }`}>
                    RISIKO {leak.riskLevel}
                  </span>
                </div>
              ))}
            </div>

            <div className="pt-4 border-t border-slate-800">
              <span className="text-slate-300 font-bold block mb-2">POTENSI KERENTANAN SISTEM:</span>
              <ul className="space-y-1.5 text-slate-400">
                {result.security.vulnerabilities.map((vuln, i) => (
                  <li key={i} className="flex items-center gap-2">
                    <span className="w-1.5 h-1.5 rounded-full bg-amber-400"></span>
                    <span>{vuln}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      )}

      {/* 6. Social Graph OSINT Tab */}
      {activeTab === 'social' && (
        <div id="tab-content-social" className="space-y-6 font-mono text-xs">
          <div className="bg-slate-950 rounded-xl border border-slate-800 p-5 space-y-4">
            <h3 className="text-sm font-bold text-white pb-2 border-b border-slate-800 flex items-center gap-2">
              <Globe className="w-4 h-4 text-emerald-400" />
              PROFIL MEDIA SOSIAL & JEJAK DIGITAL (OSINT)
            </h3>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {result.social.map((soc, idx) => (
                <div key={idx} className="p-3.5 rounded-xl bg-slate-900 border border-slate-800 flex items-center justify-between">
                  <div>
                    <span className="text-slate-400 text-[11px] block">{soc.platform}</span>
                    <span className="text-white font-bold text-xs">{soc.handle}</span>
                    {soc.followers && (
                      <span className="text-slate-500 text-[10px] block mt-0.5">Est. Followers: {soc.followers}</span>
                    )}
                  </div>
                  <span className="px-2 py-0.5 rounded bg-emerald-950/80 text-emerald-400 border border-emerald-500/40 text-[10px] font-bold">
                    {soc.status}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
